# Top of the page info
title: "Legiovue Run Report"
subtitle: "Legionella pneumophila run QC statistics and plots"
report_comment: >
  This report contains bacterial sequencing metrics for all samples ran in the pipeline.

# Other things
data_format: "yaml"
max_table_rows: 10000
show_analysis_paths: false
disable_version_detection: true

# General Statistics Table
skip_generalstats: true

# Modules/tools supported that we only want to grab
run_modules:
  - custom_content
  - kraken
  - trimmomatic
  - fastqc

# Order for reports
module_order:
  - kraken
  - trimmomatic
  - fastqc

report_section_order:
  software_versions:
    order: -1001

# Custom data here
custom_data:
  # QC CSV
  overall_quality_metrics:
    section_name: "Overall Quality Metrics"
    description: >
      This table shows the overall quality control metrics for all samples in the run
    plot_type: "table"
    pconfig:
      id: "overall_quality_metrics"
      table_title: "Overall Quality Metrics"
      namespace: "Overall Quality Metrics"
      col1_header: "Sample"
      only_defined_headers: True
      format: "{:,.0f}"
    headers:
      sample:
        scale: False
      qc_status:
        title: "QC Status"
        description: "Overall quality control outcome based on the predefined metrics and thresholds"
      lpn_abundance:
        title: "% LPN Abundance"
        description: "Overall abundance of L.pneumophila within the sample"
        min: 0
        max: 100
      num_paired_trimmed_reads:
        title: "# Paired Trimmed Reads"
        description: "Number of Paired Trimmed Reads"
      pct_paired_reads_passing_qc:
        title: "% Paired Reads Passing QC"
        description: "Percentage of read pairs retained after quality control and trimming"
        min: 0
        max: 100
      n50:
        title: "N50"
        description: "Length of the shortest contig at which 50& of the total assembly length is covered"
      num_contigs:
        title: "# Contigs"
        description: "Total number of contiguous sequences in the genome assembly"
      pct_gc:
        title: "% GC"
        description: "Percentage of guanine and cytosine bases in the assembled genome"
        min: 0
        max: 100
      assembly_len:
        title: "Assembly Length"
        description: "Total length of all contigs in the assembled genome"
      largest_contig:
        title: "Largest Contig"
        description: "Length of the longest contig in the assembly"
      st:
        title: "Sequence Type"
        description: "Sequence type based on Legionella pneumophila loci"
        scale: False
      st_approach:
        title: "Sequence Typing Approach"
        description: "Method used to determine the sequence type"
      chewbbaca_exc:
        title: "Chewbbaca Exc"
        description: "EXaCt match (100% DNA identity) with previously identified alleles"
        min: 0
        max: 100
      chewbbaca_inf:
        title: "Chewbbaca Inf"
        description: "INFerred new alleles that had no exact match in the schema but are highly similar to loci in the schema"
      chewbbaca_pct_exc:
        title: "% Chewbbaca Exc"
        description: "Percentage of EXaCt match (100% DNA identity) with previously identified alleles"
        min: 0
        max: 100
      qc_message:
        title: "QC Message"
        description: "Quality control message for failing/warning samples"

  # Chewbbaca
  chewbbaca_results_stats:
    section_name: "chewBBACA Results Statistics"
    description: >
      This table summarizes core genome allele calling results per sample with various reported metrics. <i>DOI: <a href="https://doi.org/10.1099/mgen.0.000166" target="_blank">10.1099/mgen.0.00016</a></i>
    plot_type: "table"
    pconfig:
      id: "chewbbaca_results_stats"
      table_title: "chewBBACA Results Statistics"
      namespace: "chewBBACA Results Statistics"
      col1_header: "Sample"
      only_defined_headers: True
      format: "{:,.0f}"
    headers:
      FILE:
        scale: False
      EXC:
        title: "Exact Match CDS"
        description: "Exact match (100% DNA identity) with previously identified alleles"
        min: 0
        max: 1521
      INF:
        title: "Inferred CDS"
        description: "Inferred new alleles that had no exact match in the schema but are highly similar to loci in the schema"
        min: 0
        max: 1521
      PLOT3:
        title: "PLOT5"
        description: "Possible Locus On the Tip of a contig close to the contig's 3' end"
        min: 0
        max: 1521
      PLOT5:
        title: "PLOT5"
        description: "Possible Locus On the Tip of a contig close to the contig's 5' end"
        min: 0
        max: 1521
      LOTSC:
        title: "LOTSC"
        description: "CDS where the matched representative allele is bigger than the contig containing the CDS"
        min: 0
        max: 1521
      NIPH:
        title: "Non-Informative Paralogous Hit"
        description: "Multiple CDSs from the same genome match a single locus"
        min: 0
        max: 1521
      NIPHEM:
        title: "Non-Informative Paralogous Hit Exact Match"
        description: "Multiple CDSs from the same genome are exact matches to alleles of a single locus"
        min: 0
        max: 1521
      ALM:
        title: "Allele Larger than Mode"
        description: "CDSs with a size that matches a schema locus that is above the locus size variation interval"
        min: 0
        max: 1521
      ASM:
        title: "Allele Smaller than Mode"
        description: "CDSs with a size that matches a schema locus that is below the locus size variation interval"
        min: 0
        max: 1521
      PAMA:
        title: "Paralogous Match"
        description: "CDSs that are highly similar to more than one locus"
        min: 0
        max: 1521
      LNF:
        title: "Locus Not Found"
        description: "The number of schema loci for which it was not possible to identify a similar allele in the input genome"
        min: 0
        max: 1521
      Invalid CDSs:
        title: "Invalid CDSs"
        description: "The total number of invalid CDSs"
      Classified_CDSs:
        title: "Classified CDSs"
        description: "The total number of classified CDSs (non-LNF)"
      Total_CDSs:
        title: "Total_CDSs"
        description: "The total number of predicted CDSs per genome"

  # el gato
  el_gato_sequence_based_typing:
    section_name: "El Gato Sequence Based Typing"
    description: >
      This table reports the sequence type assigned to each sample based on in silico analyis of 7 Legionella pneumophila loci. <i>URL: <a href="https://github.com/CDCgov/el_gato" target="_blank">https://github.com/CDCgov/el_gato</a></i>
    plot_type: "table"
    pconfig:
      id: "el_gato_sequence_based_typing"
      table_title: "El Gato Sequence Based Typing"
      namespace: "El Gato Sequence Based Typing"
      col1_header: "Sample"
      only_defined_headers: True
      format: "{:,.0f}"
      scale: False
    headers:
      Sample:
        scale: False
      ST:
        title: "ST"
        description: "Sequence Type"
      flaA:
        title: "flaA"
        description: "Legionella pneumophila locus (flaA)"
      pilE:
        title: "pilE"
        description: "Legionella pneumophila locus (pilE)"
      asd:
        title: "asd"
        description: "Legionella pneumophila locus (asd)"
      mip:
        title: "mip"
        description: "Legionella pneumophila locus (mip)"
      mompS:
        title: "mompS"
        description: "Legionella pneumophila locus (mompS)"
      proA:
        title: "proA"
        description: "Legionella pneumophila locus (proA)"
      neuA_neuAH:
        title: "neuA_neuAH"
        description: "Legionella pneumophila loci (neuA_neuAH)"
      approach:
        title: "Approach"
        description: "Method used to determine the sequence type"

  # Assembly Quality Report
  scored_quast_report:
    section_name: "Assembly Quality Report"
    description: >
      This table shows assembly metrics for each genome assembly with a score assigned to each metric. A final score (out of 6) is calculated for each sample upon which a rating is given.
    plot_type: "table"
    pconfig:
      id: "scored_quast_report"
      table_title: "Assembly Quality Report"
      namespace: "Assembly Quality Report"
      col1_header: "Sample"
      only_defined_headers: True
      format: "{:,.0f}"
    headers:
      sample:
        scale: False
      final_score:
        title: "Final Score"
        description: "Final sample score (out of 6)"
        scale: "RdYlGn"
        min: 0
        max: 6
      score_rating:
        title: "Final Score Rating"
        description: "Sample rating based on the final score"
        cond_formatting_rules:
          fail:
            - { "s_eq": "poor" }
            - { "s_eq": "unideal" }
          warn:
            - { "s_eq": "moderate" }
            - { "s_eq": "passing" }
          pass:
            - { "s_eq": "good" }
            - { "s_eq": "excellent" }
      num_contigs:
        title: "# Contigs"
        description: "Total number of contiguous sequences in the genome assembly"
        scale: "Greens"
      num_contigs_score:
        title: "Score (# Contigs)"
        description: "Assigned score for '# Contigs'"
        scale: "Purples"
        min: 0
        max: 1
      N50:
        title: "N50"
        description: "Length of the shortest contig at which 50& of the total assembly length is covered"
        scale: "Greens"
      N50_score:
        title: "Score (N50)"
        description: "Assigned score for 'N50'"
        scale: "Purples"
        min: 0
        max: 1
      duplication_ratio:
        title: "Duplication Ratio"
        description: "Measure of redundancy in the assembly based on aligned base coverage"
        scale: "Greens"
        min: 0
        max: 1
      duplication_ratio_score:
        title: "Score (Duplication Ratio)"
        description: "Assigned score for 'Duplication Ratio'"
        scale: "Purples"
        min: 0
        max: 1
      percent_alignment:
        title: "% Alignment"
        description: "Percentage of the assembly that aligns to the reference genome"
        scale: "Greens"
        min: 0
        max: 100
      percent_alignment_score:
        title: "Score (% Alignment)"
        description: "Assigned score for '% Alignment'"
        scale: "Purples"
        min: 0
        max: 1
      assembly_length:
        title: "Assembly Length"
        description: "Total length of all contigs in the assembled genome"
        scale: "Greens"
      assembly_length_score:
        title: "Score (Assembly Length)"
        description: "Assigned score for 'Assembly Length'"
        scale: "Purples"
        min: 0
        max: 1
      GC_content_percent:
        title: "% GC Content"
        description: "Percentage of guanine and cytosine bases in the assembled genome"
        scale: "Greens"
        min: 0
        max: 100
      GC_content_score:
        title: "Score (% GC Content)"
        description: "Assigned score for '% GC Content'"
        scale: "Purples"
        min: 0
        max: 1

# Search Pathes
sp:
  overall_quality_metrics:
    fn: "overall.qc.csv"
  chewbbaca_results_stats:
    fn: "results_statistics.tsv"
  el_gato_sequence_based_typing:
    fn: "el_gato_st.tsv"
  scored_quast_report:
    fn: "scored_quast_report.csv"
